/accelerator: cuda #cpu #cuda #cpu #mps
/enable_checkpointing: True
/devices: [0]
max_epochs: 100
callbacks:
    - ModelCheckpoint:
        /dirpath: ${__exp__.project_folder}out/models/${__exp__.name}/
        /filename: best
        save_top_k: 1
        save_last: True
        monitor: val_NDCG_@10/dataloader_idx_0 #
        mode: max
        enable_version_counter: False #If False, it will overwrite the best model
/logger:
    name: CSVLogger #WandbLogger
    params:
        save_dir: ${__exp__.project_folder}out/log/${__exp__.name}/
        version: 0 #If 0, it will overwrite the existing file